### ISSUE TITLE
Privacy statement acknowledgement button

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#990] opened 2019-06-17 19:08 UTC
Hi Stephen,

For mandatory European law I am putting a privacy statement on the site. Ideally when a user enters the site for the first time with a acknowlegement button.
How does this work? I ticked the tickbox "require acknowledgement" and the policy page that I selected is correctly displayed at new login. How do I put a button on the page? I tried [POLICYBUTTON {string %1}] but that doesn't work. Maybe some better explanation would be helpful, as this is unfortunately a mandatory thing to have in Europe.

(The GDPR plugin I tried also, but with this plugin I cannot access the site anymore,)

**Comment by Elinth** [comment] 2019-06-17 19:12
Also, can I see what user acknowledged this? I can see that it had a certain amount of visitors?

**Comment by Elinth** [comment] 2019-06-17 19:19
I got it to work with the GDPR plugin but once acknowlegded it says:  Error: the requested object was not found.
Album: {string

**Comment by sbillard** [comment] 2019-06-17 23:03
The macro you placed on the page is not correct. You have ` [POLICYBUTTON {string %1}] ` but most likely you want simply ` [POLICYBUTTON] ` I guess you copied the definition of the macro--the {string %1} signifies an optional parameter. If it is present, the user is redirected to the link represented by the parameter. If the parameter is left out he goes back to his original request.

**Comment by Elinth** [comment] 2019-06-18 18:06
Somehow the shortcode [POLICYBUTTON] does not work when I activate GDPR. Not sure if this  works as it should or if I am doing something wrong. Is it not easier to create a cookie type of message that refers to the privacy statement. It would show up at the bottom of the site and it would have a button for acknowledgement and dissapear when clicked. This is how many other sites do it. Just a thought.

**Comment by Elinth** [comment] 2019-06-18 18:13
Disregard my cookie statement comment. I just noticed the cookie consent plugin, let me give that a try..

**Comment by sbillard** [comment] 2019-06-18 23:50
I did notice that your site does not use Mod_Rewrite. Is there a reason for that? Not sure if it is the cause of the problems, though. What did happen with just the [POLICYBUTTON]? 

I also notice that your English policy text is quite definitely not the same content as the Dutch version.

**Comment by Elinth** [comment] 2019-06-19 17:45
The button is not displayed when I put the shortcode in the page. I might go the GDPR route. Is the acknowledgement logged with the user? No clue about Mod_Rewrite. I just switched it on. You can test it on my site when you switch gdpr on.

**Comment by sbillard** [comment] 2019-06-19 20:26
I do see that the checkbox/button is not displayed. I don't know right off hand why. It did work once when you had the extra "{string %1}" in the macro. So something must have changed since then.

**Comment by sbillard** [comment] 2019-06-19 20:43
I looked around some more. I checked the "Usage policy | require acknowledgement" checkbox and cleared the acknowledgements and things worked. I have left GDPR Required enabled.

The acknowledgement is recorded by user but currently that is not shown. It could be indicated and individually clearable. I think I will add that feature.

**Comment by Elinth** [comment] 2019-06-19 20:47
I see it works now! Thanks!! Why not create a log? I think it is required by law that you can see who approved the registration of personal data.

**Comment by Elinth** [comment] 2019-06-19 21:45
Is there a way to translate "Check to acknowledge the site usage policy."?

**Comment by sbillard** [comment] 2019-06-19 21:47
The string is on the general options page--should be translatable if your site is set to multi-lingual.

Would the security log be OK for the logging? That would be the simplest change.

**Comment by Elinth** [comment] 2019-06-19 22:15
I would say that the security log would do. Even if you have acknowleged, the page keeps coming up though everytime you login. Without the macro. It should come up only once before you acknowleged correct?

**Comment by sbillard** [comment] 2019-06-19 22:49
It should come up only once. It is not coming up for me when I return to the site. Once I acknowledge, I go straight to the home page, no GDPR page.

**Comment by Elinth** [comment] 2019-06-20 08:32
"The string is on the general options page--should be translatable if your site is set to multi-lingual."
If I test this it still says the same, I don't think this is translated via general options. And once I acknowledged it it takes me to the site correctly. When I logout and login after that, the page comes up first without the macro.

**Comment by sbillard** [comment] 2019-06-20 15:50
For the text, you have not created a translation of the string--the Dutch text is empty.

I think I know why the page pops up when you log out and back end. I will see how to fix that.

**Comment by sbillard** [comment] 2019-06-20 18:40
I have figured out what is wrong. When a visitor goes to the site (not logged in) he is redirected to the policy page as expected. But the login form overrides the policy acceptance, which is what should happen since we do not yet know who he is (not logged in.) Once he logs in, since he was visiting the policy page he is redirected back there even though he has already accepted the policy.

I have a fix for this in the development build. But there are major changes in the development build that will probably impact your theme customization. I think that all such changes have "been taken into account" but I would really like to verify that before you would install this release.

Could you attach a zip file of your custom theme to this ticket? I will then make sure that all works properly and even make the conversions that eventually should be applied to the theme to bypass the deprecated functions/compatibility pack needs.

The development release can be downloaded from https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/netPhotoGraphics-1.9.0.0

**Comment by Elinth** [comment] 2019-06-21 17:50
I think the policy page is currently interfering with pages that are unprotected. The contact page is not accessible when not logged in (This was previously my setting). When I click on the contact page I get the acknowledged gdpr page. When I look at the list of pages in the Gallery options I am also missing some pages, such as register.php and contact.php.

**Comment by sbillard** [comment] 2019-06-21 23:07
I think that the behavior as is should be. I cannot test your site as GDPR is currently disabled. But what should happen is that the visitor gets the GDPR page. That seems reasonable since you are about to capture his Name and e-mail address. He he should acknowledge the policy and the button should take him to the contact page.

**Closed** 2019-07-02 00:03 UTC
