### ISSUE TITLE
The bad and the ugly - MS Edge (zpMobile login form)

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#1009] opened 2019-07-19 05:12 UTC
Microsoft Edge 44.18362.1.0

![obrazek](https://user-images.githubusercontent.com/7648991/61510757-8d584f00-a9f4-11e9-98d2-d5c9511e6f39.png)

**Comment by sbillard** [comment] 2019-07-19 17:25
Works on Edge version 42.17134.1.0
I am trying to get version 44--a Windows install is in process now.

**Comment by sbillard** [comment] 2019-07-19 17:53
Also works for me on 44.18362.1.0
I presume this is from the link https://skautskagalerie.cz/admin
If not, what link?

**Comment by Mates-K1** [comment] 2019-07-19 18:09
No,.. For example https://skautskagalerie.cz/1_oddil_skautek/

My gallery is private, so first people get main page and after clik to album they get login form.

Form from your link works.

**Comment by sbillard** [comment] 2019-07-19 22:56
Ok, I can reproduce this locally now. Thanks. Some kind of CSS issue--zpMobile does its own password page.

**Comment by sbillard** [comment] 2019-07-19 23:45
So, the problem is with the jqueryMobile javascript code. Nothing much that can be done about that code other than place a ticket on the jquerymobile site. The code is altering all the checkboxes and input fields and it just does not get it right. In the case of the "show" checkbox it has duplicated the checkbox  and mucked up the positioning css that overlays the border around the input field.

The best that can be done from the nPG end is omit the checkbox for the zpmobile theme. That is fairly straight forward to do. But there is one question that needs to be answered.

Should the password input be shown or hidden?

(BTW, this failure happens in Chrome as well as Edge. I suspect it happens on all browsers since I think jquerymobile is screwing up.

**Comment by sbillard** [comment] 2019-07-20 00:36
closed via commit 89f703c0a25c32a1dc8b96cb501ee403185bcbbe

**Closed by sbillard** 2019-07-20 00:36 UTC
