### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#873] opened 2018-12-09 11:04 UTC
- [ ] **Tinymce** ( latest version 4.9.1 ) https://github.com/tinymce/tinymce/releases

- [ ] **Jquery** : Currently, netphotographics by default spews out an include for jQuery 1.11.0. It's outdated, and adds unnneccesary weight for modern browsers (which for most implementations is nearly all browsers).

**Comment by sbillard** [comment] 2018-12-09 17:52
The standard release uses jQuery 3.3.1 unless the site owner chooses differently. The option to select the version is part of the "debug" plugin. You should note that there are at present compatibility issues with some javaScript products and jQuery version 3.  At this time the the mobile theme and jCarousel_thumb_nav require jQuery version 1 to work correctly.

Anyway, even with that problem the standard release does not load jQuery 1.11.0. It falls back to jQuery 1.12. Some themes may choose to load a specific version of jQuery. There is no plan to override the choices the theme designer may have made since we have no means of knowing why the decision not to go with the version netPhotoGraphics uses.


TinyMCE is in beta for version 5. So unless there is a compelling reason to move to version 5.9.1 we will not likely make that update. Moving to any new version of these core javaScript packages requires considerable regression testing, so the value of the new version must be worth the cost of implementing it. Typically these support builds do not impact the netPhotoGraphic usage.

**Comment by sbillard** [comment] 2018-12-24 16:38
Since there is no further information on this issue and since there are absolutely no references to jQuery 1.11.0 within the code source of netPhotoGraphics I am closing this issue.

**Closed by sbillard** 2018-12-24 16:38 UTC
Labels: Cannot reproduce
