### ISSUE TITLE
flag is switched on and stuck 

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#976] opened 2019-04-29 21:08 UTC
The flag: /zp-core/locale/zh_Hans_TW/flag.png, cannot be turned off in the latest release 1.09.04.03  It was automatically switched on after the update.

**Comment by sbillard** [comment] 2019-04-29 21:43
Do you have access to your php.ini file? If so, find the line that reads `;extension=php_intl.dll` and remove the semicolon. You can see if this works by looking at the highlighted line.

<img width="513" alt="2019-04-29 14_37_00-Home Admin_ Overzicht-Installatie informatie" src="https://user-images.githubusercontent.com/2474007/56928735-9fc58b00-6a8c-11e9-9610-6ac1b19de609.png">

It will not be there if the php.ini edit works. If it persists, ask your provider to install the PHP intl module.

You can also remove the ...locale/zh_hans_TW folder on your server.

The root cause of this is that the "language name" is missing from the list when that PHP module is not present. I will cause it to be manually added which will also fix the problem. That update will be in the next Dev release I build.

**Comment by Elinth** [comment] 2019-04-30 19:23
I did the extension php_intl.dll activation successfully. The flag, however, did not disappear, the stuck flag cannot be selected in the main options. Eventually I deleted the folder.

**Comment by sbillard** [comment] 2019-04-30 21:23
Thanks for the update. Looking at the locales your server supports, it seems that zh_hans_TW is not one of them. Who knew. I guess that zh_Hant_TW is the correct locale. I will update that. Also, the reason why the flag would not go away was that the "name" was an empty string. I will make sure that the function that substitutes for the intl module will at least return the locale code if there is not a language "name".

**Closed** 2019-05-21 18:10 UTC
